version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 2005
      DATABASE_NAME: postgres
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 3600s
      JWT_REFRESH_EXPIRES_IN: 7d

volumes:
  db_data: